apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      test: posts
  template:
    metadata:
      labels:
        test: posts
    spec:
      containers:
        - name: posts
          image: tkoriginal/posts:0.0.1